config/routes.rb
Rails.application.routes.draw do

   resources :categories
resources :books
  get 'pages/home'
  get    '/login',   to: 'sessions#new'
   post   '/login',   to: 'sessions#create'
   delete '/logout',  to: 'sessions#destroy'

   root 'pages#home'


   resources :book do
     resources :likes
   end
resources :users
get '/users/:id', to: 'users#show'

resources :messages, only:[:create]

  resources :users, only:[:new, :create] do
   resources :chats, only: [:index, :show, :create]
  end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :description, presence: true
  has_one_attached :avatar
  belongs_to :user, optional: true
   belongs_to :category, optional: true

   has_many :likes, dependent: :destroy


end

app/models/category.rb
class Category < ApplicationRecord
has_many :books
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
    has_many :subscriptions, dependent: :destroy
    has_many :users, through: :subscriptions
    validates :identifier, presence: true, uniqueness: true,    case_sensitive: false
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :chat
 belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, :uniqueness => { :case_sensitive => false }
  validates :password, presence: true, confirmation: true, :on => :create
  has_one_attached :avatar
  validates :agreement, presence: true
  has_many :books

  has_many :likes, dependent: :destroy


  has_secure_password


  has_many :messages
  has_many :subscriptions
  has_many :chats, through: :subscriptions
  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
      existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map {|subscription| subscription.user})
    end
    existing_chat_users.uniq
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    if logged_in?
      @book = Book.new
    else
redirect_to root_path
end
  end

  def create
    @book = Book.new(book_params)
    if @book.valid?
      @user = User.find(session[:user_id])
      @user.books << @book
      @book.save
      redirect_to @user
    end
  end


  def index
    if logged_in?
    @books = Book.all
  else
redirect_to root_path
end
  end

  def show
    if logged_in?
    @book=Book.find(params[:id])
    @related_posts = Book.where(category: @book.category_id)
  else
redirect_to root_path
end
  end

  def edit
    if logged_in?
    @book = Book.find(params[:id])

  else
    redirect_to root_path
  end
end

def update
  @book = Book.find(params[:id])

  if @book.update_attributes(book_params)
    redirect_to @book
  else
    render 'edit'
  end
end

def destroy
  @book = Book.find(params[:id])
  @book.destroy
  respond_to do |format|
    format.html
    format.js
  end
end
private

def book_params
  params.require(:book).permit(:title, :author, :description, :user_id, :category_id, :avatar)
end

end

app/controllers/chats_controller.rb
require 'securerandom'

class ChatsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :require_login

  def index
    chats = current_user.chats
    @existing_chats_users = current_user.existing_chats_users
  end

  def create
    @other_user = User.find(params[:other_user])
    @chat = find_chat(@other_user) || Chat.new(identifier: SecureRandom.hex)
    if !@chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
    redirect_to user_chat_path(current_user, @chat,  :other_user => @other_user.id)
  end

  def show
    @other_user = User.find(params[:other_user])
    @chat = Chat.find_by(id: params[:id])
    @message = Message.new
  end

  private

  def find_chat(second_user)
    chats = current_user.chats
    chats.each do |chat|
      chat.subscriptions.each do |s|
        if s.user_id == second_user.id
          return chat
        end
      end
    end
    nil
  end
  def require_login
    redirect_to new_session_path unless logged_in?
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_book
before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @book.likes.create(user_id: current_user.id)
    end
    redirect_to book_path(@book)
  end

  def destroy
  if !(already_liked?)
    flash[:notice] = "Cannot unlike"
  else
    @like.destroy
  end
  redirect_to book_path(@book)
end

 private
 def find_book
   @book = Book.find(params[:book_id])
 end
 def already_liked?
  Like.where(user_id: current_user.id, book_id:
  params[:book_id]).exists?
end
def find_like
   @like = @book.likes.find(params[:id])
end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
      message = Message.new(message_params)
      message.user = current_user
      if message.save
        #broadcasting out to messages channel including the chat_id so messages are broadcasted to specific chat only
        ActionCable.server.broadcast( "messages_#{message_params[:chat_id]}",
        #message and user hold the data we render on the page using javascript
        message: message.content,
        user: message.user.first_name
        )
      else
        redirect_to chats_path
      end
    end

  private

      def message_params
        params.require(:message).permit(:content, :chat_id)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    render :layout => false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @user = User.new
    render :layout => false
  end


  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      log_in @user
      redirect_to @user

    end

  end

  def index
    if logged_in?
      @user = User.all
    else
      redirect_to root_path
    end
  end

  def show
    if logged_in?
    @user = User.find(params[:id])
    @user_books = Book.where(user_id: @user)
    render :layout => false
  else
redirect_to root_path
end
  end


  def edit
    if logged_in?
    @user = User.find(params[:id])
  else
redirect_to root_path
end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to @user
    else
      puts @user.errors.details
      render 'edit'
    end

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.js
    end
  end



  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :agreement,:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
  session[:user_id] = user.id
 end

 def current_user
   if session[:user_id]
     @current_user ||= User.find_by( id: session[:user_id])
   end
 end

 def logged_in?

   session[:user_id] ? true : false
 end

 def log_out
   session[:user_id] ? true : false
   session.delete(:user_id)
session[:user_id] = nil
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/destroy.js.erb
var deleteitem = document.getElementById(‘book-<%=@user_books.id%>’);
deleteitem.remove()

app/views/books/edit.html.erb
<h1>Edit Your Book</h1>

<%= form_for @book do |f| %>


<label>Author Name:</label><br>
<%= f.text_field :author %><br>

<label>title:</label><br>
 <%= f.text_field :title %><br>

 <label>Description:</label><br>
<%= f.text_area :description, :cols => 30, :rows => 10 %><br>

<label>Edit Book Picture:</label><br>
 <%= f.file_field :avatar, direct_upload: true %></p>


   <p>
   <%= f.submit "Save Changes" %>
   </p>
   <%end%>

app/views/books/index.html.erb
<%=link_to "Profile", user_path(session[:user_id]) %>


<% @books.each do |b| %>

<p><%= image_tag(b.avatar) if b.avatar.attached?%></p>
  <p><%= b.title %></p>
  <p><%= b.author %></p>
  <%=b.description.truncate(10)%> <br>

  <p><a href="/books/<%=b.id%>">VIEW BOOK</a></p>

  <% end %>

app/views/books/new.html.erb
<h1>Create Your Book</h1>
<%= form_for @book do |f| %>

<label>Author Name:</label><br>
<%= f.text_field :author %><br>

<label>Title:</label><br>
 <%= f.text_field :title %><br>

 <label>Description:</label><br>
<%= f.text_area :description, :cols => 30, :rows => 10 %>

<p><%= f.label :category_id, "Select Category"%> <br>
  <%= f.select(:category_id, Category.all.collect{ |category| ["#{category.id}. #{category.name}"]
                                        }, {})%>
 <p><%= f.file_field :avatar, direct_upload: true %></p>
<p>
<%= f.submit %>
</p>


<%end%>

app/views/books/show.html.erb
<style media="screen">
.img-ic img{
  height:60px;
  width:60px;
}
a img{
  height:35px;
  width:35px;
}
</style>
<div class="book-show">


<h1>Book:</h1>



<%= image_tag(@book.avatar) if @book.avatar.attached? %><br>
      <p><%= @book.author %></p>
      <p><%= @book.title %></p>
      <p><%= @book.description %></p>

            <% if session[:user_id] == @book.user_id %><br>
<a href="/books/<%=@book.id%>/edit" > <img src="/assets/edit.png"></a>

<% end %><br>
<p><%= @book.likes.count %> <%= (@book.likes.count) == 1 ? 'Like' : 'Likes'%></p>
<div class="img-ic">

<% pre_like = @book.likes.find { |like| like.user_id == current_user.id} %>
       <% if pre_like %>
         <%= link_to  book_like_path(@book, pre_like), method: :delete, class: 'like-ic' do %>

         <%= image_tag("/assets/dislike.png") %>
       <%end%>
     <% else %>
       <%= link_to  book_likes_path(@book), method: :book, class: 'dislike-ic' do %>
       <%= image_tag("/assets/like.png") %>
       <%end%>
       <% end %>

     </div>
</div>

app/views/chats/index.html.erb
<h1>MY Chats</h1>
<ul>
 <% if @existing_chats_users %>
   <% @existing_chats_users.each do |other_user| %>
    <% if other_user != current_user %>
      <li>
        <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
        <%= other_user.first_name %>
        <% end %>
      </li>
     <% end %>
   <% end %>
  <% end %>
</ul>

app/views/chats/show.html.erb
<div>
  <h5>Chat with <%= @other_user.first_name %></h5>
  <% if @chat.messages.any? %>
    <div id="messages">
      <%= render partial: 'messages/message', collection: @chat.messages.order(id: :asc)%>
    </div>
  <%else%>
    <div id="messages">
    </div>
  <%end%>
</div>
<%= render partial: 'messages/message_form', locals: {message: @message, chat: @chat}%>
<script>
  createMessageChannel();
  // app/assets/javascripts/channels/messages.js
  messageForm();
  // app/assets/javascripts/messages_form.js
</script>

app/views/messages/_message.html.erb
<p>
    <%= message.user.first_name.capitalize %>: <%=message.content%> <br>
  <span>  Sent: <%= message.created_at.strftime('%b %d, %C%y %r') %></span> </p>

app/views/messages/_message_form.html.erb
<%=form_for message, remote: true,authenticity_token: true do |f|%>
<p>
  <%= f.text_field :content, data: {text_field: "message"}%>
<!-- this hidden field is for the MessagesController and Action Cable to keep track of what chat this message belongs to -->
<%= f.hidden_field :chat_id, value: chat.id %>
<%= f.submit 'SEND'%>
</p>
<%end%>

app/views/users/destroy.js.erb
$("#book-<%= @book.id %>").fadeOut();

app/views/users/edit.html.erb
<h1>Change Your Profile </h1>
<%= form_for @user do |f| %>

<label>First Name:</label><br>
 <%= f.text_field :first_name %><br>

 <label>Last Name:</label><br>
  <%= f.text_field :last_name %><br>

<label>Email:</label><br>
 <%= f.email_field :email %><br>


<label>Edit Photo:</label><br>
 <%= f.file_field :avatar, direct_upload: true %></p>


   <p>
   <%= f.submit "Save Changes" %>
   </p>
   <%end%>

app/views/users/index.html.erb
<h2>All Users</h2>
<table>
  <tr>
    <th>First Name</th>

    
    <th>Last Name</th>

    <th>Email</th>


  </tr>

  <% @user.each do |u| %>
  <tr>
    <td><%= u.first_name %></td>
    <td><%= u.last_name %></td>
    <td><%= u.email %></td>




    <% end %>

  </tr>
</table>

app/views/users/new.html.erb
<style>
  body{
   background-image:url('https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQiaayl6XuInornOq4LDrWJXUiMzkOlC1nnDcocebbMpAR8wqFt1Q');
    margin: 0;
    font: 11px/20px 'Courgette';

  }

  h1{
    text-align:center;
    color:black;
    font-size:40px;
    padding:1%;
    text-align:center;
  }

  .left {
    position: absolute;
    left: 32%;
    right: 50%;
    top: 50px;
    bottom: 10px;
    width: 500px;
    height:600px;
    background: rgb(247, 246, 212);
      /* transform: rotateX(20deg); */
      border-radius: 20px;
      box-shadow:
        inset 2px 2px 2px rgba(255,255,255,.2),
        2px 2px 3px rgba(0,0,0,.2);
  }

  .page-inner {
    position: absolute;
  /* transform: rotateX(20deg); */
    top: 30px;
     bottom: 20px;
    left: 47px;
    right: 15px;
    outline: none;

    background: linear-gradient(
      to bottom,
      transparent,
      transparent 19px,
      rgba(0,0,0,.2),
      rgba(0,0,0,.2) 1px
    );
    background-size: 100% 20px;
    box-shadow:
      0 -1px 0 rgba(0,0,0,0.2),
      0 -5px 0 rgb(247, 246, 212),
      0 -6px 0 rgba(0,0,0,0.4);

    font: 11px/20px 'Courgette';
    color: #555;
    text-align: left;
  }
  .left::before {
  content: '';
  position: absolute;
  left: 45px;
  height: 100%;
  width: 2px;
  background: rgba(255,0,0,0.4);
}

</style>
<h1>LibroSwap</h1>
  <div class="left">
    <div class="page-inner" >
<h2>Create Your Account</h2>

<%= form_for(@user) do |f| %>

<label>First Name:</label><br>
  <%= f.text_field :first_name %><br>

  <label>Last Name:</label><br>
    <%= f.text_field :last_name %><br>

  <label>Email:</label><br>
    <%= f.email_field :email %><br>


    <label> Password: </label> <br>
    <%= f.password_field :password %><br>


<p><%= f.file_field :avatar, direct_upload: true %></p>

<label> Agreement:</label>
    <%= f.check_box :agreement, required: true %> I have read and agree to the Terms and Conditions and Privacy Policy  <br/>

<p>
<%= f.submit %>
</p>

<%end%>
<%= link_to 'Log in', login_path %>

</div>


</div>


<script>

</script>

app/views/users/show.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<style>

  body {
    background: rgb(225, 228, 232);
    background-image:url('https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQiaayl6XuInornOq4LDrWJXUiMzkOlC1nnDcocebbMpAR8wqFt1Q');
  }
  img{
    height: 200px;
    width: 200px;
  }
  /** Notebook Base **/
  .notebook {
    position: absolute;
    width: 900px;
    height:600px;
    top: 30%;
    left: 35%;
    margin: -175px 0 0 -250px;
    background-color: #444;
    background-image:
    -webkit-repeating-radial-gradient(
    center center,
    rgba(0,0,0,.5),
    rgba(0,0,0,.5) 2px,
    transparent 2px,
    transparent 100%
    );
    background-image:
    repeating-radial-gradient(
    center center,
    rgba(0,0,0,.5),
    rgba(0,0,0,.5) 2px,
    transparent 2px,
    transparent 100%
    );
    background-size: 4px 4px;
    border-radius: 15px;
    box-shadow:
    inset 2px 2px 2px rgba(255,255,255,.2),
    2px 2px 3px rgba(0,0,0,.2);
  }
  /** Left Page **/
  .left {
    position: absolute;
    left: 10px; right: 50%;
    top: 10px; bottom: 10px;
    background: rgb(247, 246, 212);
    border-radius: 10px 0 0 10px;
    box-shadow:
    inset -10px 0 30px -10px rgba(0,0,0,.3),
    -2px 2px 1px rgba(0,0,0,.8);
  }
  /** Right Page **/
  .right {
    position: absolute;
    left: 50%; right: 10px;
    top: 10px; bottom: 10px;
    background: rgb(247, 246, 212);
    border-radius: 0 10px 10px 0;
    box-shadow:
    inset 10px 0 30px -10px rgba(0,0,0,.3),
    2px 2px 1px rgba(0,0,0,.8);
  }
  /** Page inner **/
  .page-inner {
    position: absolute;
    top: 30px; bottom: 20px;
    left: 15px; right: 15px;
    outline: none;
    overflow: scroll;
    background: linear-gradient(
    to bottom,
    transparent,
    transparent 19px,
    rgba(0,0,0,.2),
    rgba(0,0,0,.2) 1px
    );
    background-size: 100% 20px;
    box-shadow:
    0 -1px 0 rgba(0,0,0,0.2),
    0 -5px 0 rgb(247, 246, 212),
    0 -6px 0 rgba(0,0,0,0.4);
    font: 14px/20px 'Courgette';
    color: #555;
    text-align: left;
  }
  ::-webkit-scrollbar {
    display: none;
  }


  #mySidenav a {
    position: absolute;
    left: -150px;
    transition: 0.3s;
    padding: 15px;
    width: 170px;
    text-decoration: none;
    font-size: 20px;
    text-align: center;
    color: black;
    border-radius: 0 5px 5px 0;
  }

  #mySidenav a:hover {
    left: 0;
  }

  #home {
    top: 20px;
  background-image: url(/assets/tape.png);
  background-size: cover;
  }

  #profile {
    top: 80px;
  background-image: url(/assets/tape.png);
  background-size: cover;
  }

  #mymessage {
    top: 140px;
  background-image: url(/assets/tape.png);
  background-size: cover;

  }

  #categories {
    top: 200px;
  background-image: url(/assets/tape.png);
  background-size: cover;

  }

  #lbook {
    top: 260px;
  background-image: url(/assets/tape.png);
  background-size: cover;

  }



    .sticky {
      box-sizing: border-box;
      height: 300px;
      width: 300px;
      background: linear-gradient(to bottom, #feeb8e 0%, #ffefa1 100%);
      padding: 25px;
      border-top-right-radius: 10px 100px;
      border-bottom-right-radius: 10px 100px;
      border-top-left-radius: 5px 50px;
      border-bottom-left-radius: 35px 50px;
      box-shadow: 6px 6px 10px 2px #999;
      margin-top: 20px;
      position: relative;
      transform: translate(25%, -1%)
    }
    .sticky:before {
      content: "";
      position: absolute;
      top: -15px;
      left: 50%;
      transform: translateX(-50%);
      width: 30px;
      height: 35px;
      background-image: url(https://dk7jqzmygmr3q.cloudfront.net/ml/neducatio/5b633eca-5c8f-4d4b-8ce0-cf9618e9aec6.image?v=1&type=png);
      background-size: cover;
    }
    .sticky:after {
      content: "";
      position: absolute;
      height: 300px;
      width: 15px;
      border-top-right-radius: 50%;
      border-bottom-right-radius: 50%;
      top: 0;
      left: 0;
    }
    .sticky img{
      height:50px;
      width:50px
    }

    .prof-img img{
      height:50px;
      width:50px;
    }

  </style>


  <%= render 'layouts/sidenav'%>

  <div class="notebook">
    <div class="left">
      <div class="page-inner" >

        <h1> Welcome <%= @user.first_name %> </h1>

        <%= image_tag(@user.avatar) if @user.avatar.attached?%>



        <h3>First Name: <%= @user.first_name %></h3> <br>
        <h3>Last Name: <%= @user.last_name %></h3> <br>
        <h3>Email: <%= @user.email %></h3><br>

        <% if @user == current_user %>
<div class="prof-img">

  <a href="/users/<%=@user.id%>/edit" > <img src="/assets/profile.png"></a>
      <%= link_to(image_tag("/assets/log.png"), logout_path, method: :delete) %>
    </div>


    <%end%>


  </div>
</div>
    <div class="right">
      <div class="page-inner" >

        <% if @user == current_user %>

        <% @user_books.each do |b| %>
        <div id="book-<%=b.id%>">

        <div class="sticky">


          <div class="main-grid">
            Title: <%= b.title %><br>
            Author:  <%= b.author %><br>
            <div class="img">
            <%= image_tag(b.avatar) if b.avatar.attached?%>
          </div>
            Description:  <%=b.description.truncate(10)%> <br>
              <p><%= b.likes.count %> <%= (b.likes.count) == 1 ? 'Like' : 'Likes'%></p>
          <a href="/books/<%=b.id%>" > <img src="/assets/book.png"></a>
          <%= link_to(image_tag("/assets/delete.png"), user_path(b.id), method: :delete, :remote => true) %>
          </div>
          </div>


        </div>
        <% end %>





        <% else %>

        <% books = Book.where(user_id: @user.id)%>

        <% books.each do |b| %>
        <div class="sticky">
          <div class="main-grid">
            <%= image_tag(b.avatar) if b.avatar.attached?%>
            Title:  <%= b.title %><br>
            Author:  <%= b.author %><br>
            Description:  <%=b.description.truncate(10)%> <br>
            <a href="/books/<%=b.id%>">VIew BOok</a>
          </div>
        </div>
        <% end %>
        <%end%>


      </div>
    </div>
  </div>