config/routes.rb
Rails.application.routes.draw do

   resources :categories
resources :books
  get 'pages/home'
  get    '/login',   to: 'sessions#new'
   post   '/login',   to: 'sessions#create'
   delete '/logout',  to: 'sessions#destroy'

   root 'pages#home'


   resources :book do
     resources :likes
   end
resources :users
get '/users/:id', to: 'users#show'

resources :messages, only:[:create]

  resources :users, only:[:new, :create] do
   resources :chats, only: [:index, :show, :create]
  end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :description, presence: true
  has_one_attached :avatar
  belongs_to :user, optional: true
   belongs_to :category, optional: true

   has_many :likes, dependent: :destroy


end

app/models/category.rb
class Category < ApplicationRecord
has_many :books
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
    has_many :subscriptions, dependent: :destroy
    has_many :users, through: :subscriptions
    validates :identifier, presence: true, uniqueness: true,    case_sensitive: false
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :chat
 belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, :uniqueness => { :case_sensitive => false }
  validates :password, presence: true, confirmation: true, :on => :create
  has_one_attached :avatar
  validates :agreement, presence: true
  has_many :books

  has_many :likes, dependent: :destroy


  has_secure_password


  has_many :messages
  has_many :subscriptions
  has_many :chats, through: :subscriptions
  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
      existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map {|subscription| subscription.user})
    end
    existing_chat_users.uniq
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    if logged_in?
      @book = Book.new
    else
redirect_to root_path
end
  end

  def create
    @book = Book.new(book_params)
    if @book.valid?
      @user = User.find(session[:user_id])
      @user.books << @book
      @book.save
      redirect_to @user
    end
  end


  def index
    if logged_in?
    @books = Book.all
  else
redirect_to root_path
end
  end

  def show
    if logged_in?
    @book=Book.find(params[:id])
    @related_posts = Book.where(category: @book.category_id)
  else
redirect_to root_path
end
  end

  def edit
    if logged_in?
    @book = Book.find(params[:id])

  else
    redirect_to root_path
  end
end

def update
  @book = Book.find(params[:id])

  if @book.update_attributes(book_params)
    redirect_to @book
  else
    render 'edit'
  end
end

def destroy
  @book = Book.find(params[:id])
  @book.destroy
  respond_to do |format|
    format.html
    format.js
  end
end
private

def book_params
  params.require(:book).permit(:title, :author, :description, :user_id, :category_id, :avatar)
end

end

app/controllers/chats_controller.rb
require 'securerandom'

class ChatsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :require_login

  def index
    chats = current_user.chats
    @existing_chats_users = current_user.existing_chats_users
  end

  def create
    @other_user = User.find(params[:other_user])
    @chat = find_chat(@other_user) || Chat.new(identifier: SecureRandom.hex)
    if !@chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
    redirect_to user_chat_path(current_user, @chat,  :other_user => @other_user.id)
  end

  def show
    @other_user = User.find(params[:other_user])
    @chat = Chat.find_by(id: params[:id])
    @message = Message.new
  end

  private

  def find_chat(second_user)
    chats = current_user.chats
    chats.each do |chat|
      chat.subscriptions.each do |s|
        if s.user_id == second_user.id
          return chat
        end
      end
    end
    nil
  end
  def require_login
    redirect_to new_session_path unless logged_in?
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_book
before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @book.likes.create(user_id: current_user.id)
    end
    redirect_to book_path(@book)
  end

  def destroy
  if !(already_liked?)
    flash[:notice] = "Cannot unlike"
  else
    @like.destroy
  end
  redirect_to book_path(@book)
end

 private
 def find_book
   @book = Book.find(params[:book_id])
 end
 def already_liked?
  Like.where(user_id: current_user.id, book_id:
  params[:book_id]).exists?
end
def find_like
   @like = @book.likes.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
  session[:user_id] = user.id
 end

 def current_user
   if session[:user_id]
     @current_user ||= User.find_by( id: session[:user_id])
   end
 end

 def logged_in?

   session[:user_id] ? true : false
 end

 def log_out
   session[:user_id] ? true : false
   session.delete(:user_id)
session[:user_id] = nil
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sidenav.html.erb
<div id="mySidenav" class="sidenav">
  <a href="<%=root_path%>" id="home">Home</a>
  <a href="<%=user_path(session[:user_id]) %>" id="profile">Profile</a>
  <a href="<%=  user_chats_path(session[:user_id])%>" id="mymessage">Messages</a>
  <a href=" <%= categories_path %>" id="categories">Categories</a>
  <a href="<%=  new_book_path %>" id="lbook">List A Book</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibroSwap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/2903eb4599.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  </head>

  <%= render 'layouts/sidenav'%>
  <body>

    <div class="notebook">
      <div class="left">
        <div class="page-inner" >

          <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <%= yield %>

      </div>

    </div>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<style>
  body{
   background-image:url('https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQiaayl6XuInornOq4LDrWJXUiMzkOlC1nnDcocebbMpAR8wqFt1Q');
    margin: 0;
    font: 11px/20px 'Courgette';

  }

  h1{
    text-align:center;
    color:black;
    font-size:40px;
    padding:1%;
    text-align:center;
  }

  .notebook {
    position: absolute;
    width: 900px;
    height:600px;
    top: 35%;
     left: 35%;
    margin: -175px 0 0 -250px;

      );
    background-size: 4px 4px;

    border-radius: 15px;
    box-shadow:
      inset 2px 2px 2px rgba(255,255,255,.2),
      2px 2px 3px rgba(0,0,0,.2);
  }

  .left {
    position: absolute;
    left: 10px; right: 50%;
    top: 10px; bottom: 10px;
    background: rgb(247, 246, 212);
    border-radius: 10px 0 0 10px;
    box-shadow:
    inset -10px 0 30px -10px rgba(0,0,0,.3),
    -2px 2px 1px rgba(0,0,0,.8);
  }
  /** Right Page **/
  .right {
    position: absolute;
    left: 50%; right: 10px;
    top: 10px; bottom: 10px;
    background: rgb(247, 246, 212);
    border-radius: 0 10px 10px 0;
    box-shadow:
    inset 10px 0 30px -10px rgba(0,0,0,.3),
    2px 2px 1px rgba(0,0,0,.8);
  }
  /** Page inner **/
  .page-inner {
    position: absolute;
    top: 30px; bottom: 20px;
    left: 15px; right: 15px;
    outline: none;
    overflow: scroll;
    background: linear-gradient(
    to bottom,
    transparent,
    transparent 19px,
    rgba(0,0,0,.2),
    rgba(0,0,0,.2) 1px
    );
    background-size: 100% 20px;
    box-shadow:
    0 -1px 0 rgba(0,0,0,0.2),
    0 -5px 0 rgb(247, 246, 212),
    0 -6px 0 rgba(0,0,0,0.4);
    font: 14px/20px 'Courgette';
    color: #555;
    text-align: left;
  }
  ::-webkit-scrollbar {
    display: none;
  }


  #mySidenav a {
    position: absolute;
    left: -150px;
    transition: 0.3s;
    padding: 15px;
    width: 170px;
    text-decoration: none;
    font-size: 20px;
    text-align: center;
    color: black;
    border-radius: 0 5px 5px 0;
  }

  #mySidenav a:hover {
    left: 0;
  }

  #home {
    top: 20px;
  background-image: url(/assets/tape.png);
  background-size: cover;
  }

  #profile {
    top: 80px;
  background-image: url(/assets/tape.png);
  background-size: cover;
  }

  #mymessage {
    top: 140px;
  background-image: url(/assets/tape.png);
  background-size: cover;

  }

  #categories {
    top: 200px;
  background-image: url(/assets/tape.png);
  background-size: cover;

  }

  #lbook {
    top: 260px;
  background-image: url(/assets/tape.png);
  background-size: cover;

  }


      .sticky {
        box-sizing: border-box;
        height: 350px;
        width: 300px;
        background: linear-gradient(to bottom,  #feeb8e 0%, #ffefa1 100%);
        padding: 25px;
        border-top-right-radius: 10px 100px;
        border-bottom-right-radius: 10px 100px;
        border-top-left-radius: 5px 50px;
        border-bottom-left-radius: 5px 50px;
        box-shadow: 6px 6px 10px 2px #999;
        margin-top: 20px;
        position: relative;
        transform: translate(25%, -1%)
      }
      .sticky:before {
        content: "";
        position: absolute;
        top: -15px;
        left: 50%;
        transform: translateX(-50%);
        width: 30px;
        height: 35px;
        background-image: url(https://dk7jqzmygmr3q.cloudfront.net/ml/neducatio/5b633eca-5c8f-4d4b-8ce0-cf9618e9aec6.image?v=1&type=png);
        background-size: cover;
      }

    .agreement{
    display: block;
    margin:auto;
    box-shadow: rgba(0,0,0,0.5) 0px 3px 20px;
    background:white;
    background-image: linear-gradient(white, transparent, transparent);
    width:340px;
    height: 250px;
    margin:0;
    position: relative;
    top:30%;
    left:45%;
      overflow: scroll;
    transform: translate(-50%, -50%);
  }
  p{
    font-size:15px;
    font-weight:bold;
    padding:5%;
  }
  ::-webkit-scrollbar {
    display: none;
  }
  h4{
    font-size:15px;
    font-weight:bold;
    padding:16%;

  }
</style>
<% if logged_in? %>
<%= render 'layouts/sidenav'%>
<h1>LibroSwap</h1>
<div class="notebook">
<div class="left">
  <div class="page-inner" >
    <div class="sticky">
      <h2>About Us:</h2>
      <p>We are a trading book company to help student's trade books that they don't need, this company helps students with financial problems and that are not looking to spend money buying book for classes</p>
    </div>

</div>
</div>
<div class="right">
  <div class="page-inner" >
    <div class="sticky">
      <h2>Agreement:</h2>
      <p>Before Signing up you must have to agree with our policy and know that we don't tolorate any bad behaviors on our website</p>
      <p>If you trade a book and don't recieve the right book and we are contact by the user we will terminate your account if our record match the report</p>

    </div>


    </div>
    </div>
    </div>

<% else %>
<h1>LibroSwap</h1>
<div class="notebook">
<div class="left">
  <div class="page-inner" >
    <div class="sticky">
      <h2>About Us:</h2>
      <p>We are a trading book company to help student's trade books that they don't need, this company helps students with financial problems and that are not looking to spend money buying book for classes</p>
    </div>

    <h4>  <%= link_to 'Log in', login_path %><br>
    New Admin? <%= link_to "Sign up now!", new_user_path %></h4>
</div>

</div>
<div class="right">
  <div class="page-inner" >
    <div class="sticky">
      <h2>Agreement:</h2>
      <p>Before Signing up you must have to agree with our policy and know that we don't tolorate any bad behaviors on our website</p>
      <p>If you trade a book and don't recieve the right book and we are contact by the user we will terminate your account if our record match the report</p>

    </div>

    </div>
    </div>
    </div>
<%end%>